# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
# This file was contributed by EdwinBetanc0urt@outlook.com from ERP Consultores y Asociados, C.A

name: gRPC-API Package Publish

on:
  release:
    types: 
      - created

jobs:
  publish-npm:
    name: Publish NPM Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Node configuration
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - name: Install node dependencies
        run: npm ci # if a package.lock exists

      - name: Generate proto stub
        run: npm run stub --if-present

      - name: Publish NPM Registry
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


  publish-gpr:
    name: Publish GitHub Package Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Node configuration
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'
          # Defaults to the user or organization that owns the workflow file
          scope: '@adempiere'

      - name: Install node dependencies
        run: npm ci # if a package.lock exists

      - name: Generate proto stub
        run: npm run stub --if-present

      - name: Publish GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
